# Generated by Django 4.2.11 on 2025-07-25 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the search session", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the search objectives",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("defining_search", "Defining Search"),
                            ("ready_to_execute", "Ready to Execute"),
                            ("executing", "Executing"),
                            ("processing_results", "Processing Results"),
                            ("ready_for_review", "Ready for Review"),
                            ("under_review", "Under Review"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status in the 9-state workflow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When search execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When search was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the search session"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing sessions",
                    ),
                ),
                (
                    "total_queries",
                    models.IntegerField(
                        default=0, help_text="Total number of search queries"
                    ),
                ),
                (
                    "total_results",
                    models.IntegerField(
                        default=0, help_text="Total number of results found"
                    ),
                ),
                (
                    "reviewed_results",
                    models.IntegerField(
                        default=0, help_text="Number of results reviewed"
                    ),
                ),
                (
                    "included_results",
                    models.IntegerField(
                        default=0,
                        help_text="Number of results included in final selection",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who created this search session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Session Created"),
                            ("status_changed", "Status Changed"),
                            ("search_defined", "Search Defined"),
                            ("search_executed", "Search Executed"),
                            ("results_processed", "Results Processed"),
                            ("review_started", "Review Started"),
                            ("review_completed", "Review Completed"),
                            ("exported", "Data Exported"),
                            ("shared", "Session Shared"),
                            ("note_added", "Note Added"),
                            ("settings_changed", "Settings Changed"),
                        ],
                        help_text="Type of activity performed",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the activity"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity metadata (e.g., old/new values)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The search session this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="review_manager.searchsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Session activities",
                "db_table": "session_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-created_at"],
                        name="session_act_session_81f156_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="session_act_activit_f6e904_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="session_act_created_eefd6e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(fields=["status"], name="search_sess_status_f03a9a_idx"),
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["owner", "-created_at"], name="search_sess_owner_i_94ef06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchsession",
            index=models.Index(
                fields=["created_at"], name="search_sess_created_fb705b_idx"
            ),
        ),
    ]
