# Generated by Django 4.2.11 on 2025-07-25 01:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("review_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("prisma_flow", "PRISMA Flow Diagram"),
                            ("full_report", "Full PRISMA Report"),
                            ("included_studies", "Included Studies List"),
                            ("excluded_studies", "Excluded Studies with Reasons"),
                            ("search_strategy", "Search Strategy Documentation"),
                            ("data_export", "Raw Data Export"),
                        ],
                        help_text="Type of report",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("xlsx", "Excel Spreadsheet"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("bibtex", "BibTeX"),
                        ],
                        help_text="Export file format",
                        max_length=10,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Generated file name", max_length=255),
                ),
                (
                    "file_path",
                    models.FileField(
                        help_text="Path to generated file", upload_to="reports/%Y/%m/"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(help_text="File size in bytes"),
                ),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Report description or notes"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used to generate report"
                    ),
                ),
                (
                    "total_results",
                    models.IntegerField(default=0, help_text="Total results in report"),
                ),
                (
                    "included_results",
                    models.IntegerField(
                        default=0, help_text="Number of included results"
                    ),
                ),
                (
                    "excluded_results",
                    models.IntegerField(
                        default=0, help_text="Number of excluded results"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When report was generated"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When report file will be deleted",
                        null=True,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="User who generated this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The search session this report is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_reports",
                        to="review_manager.searchsession",
                    ),
                ),
            ],
            options={
                "db_table": "export_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "report_type"],
                        name="export_repo_session_b6ca1a_idx",
                    ),
                    models.Index(
                        fields=["generated_by", "-generated_at"],
                        name="export_repo_generat_dcfeaa_idx",
                    ),
                ],
            },
        ),
    ]
