# Generated by Django 4.2.11 on 2025-07-27 00:31

from django.db import migrations


def populate_initial_config(apps, schema_editor):
    """Populate initial configuration values."""
    Configuration = apps.get_model('core', 'Configuration')
    
    # Initial system configuration
    initial_config = {
        'search': {
            'default_num_results': 100,
            'default_location': None,
            'default_language': 'en',
            'default_file_types': ['pdf'],
        },
        'api': {
            'serper_timeout': 30,
            'rate_limit_per_minute': 100,
            'max_retries': 3,
        },
        'processing': {
            'batch_size': 50,
            'cache_ttl': 3600,
            'duplicate_threshold': 0.85,
        }
    }
    
    Configuration.objects.create(
        key='system_config',
        value=initial_config,
        description='System-wide configuration for Thesis Grey application'
    )


def reverse_populate_config(apps, schema_editor):
    """Remove initial configuration."""
    Configuration = apps.get_model('core', 'Configuration')
    Configuration.objects.filter(key='system_config').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_initial_config, reverse_populate_config),
    ]
