# Generated by Django 4.2.11 on 2025-07-26 23:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("review_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "population_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terms describing the population (e.g., 'elderly', 'children with autism')",
                        size=None,
                    ),
                ),
                (
                    "interest_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terms describing the intervention/interest (e.g., 'telehealth', 'cognitive therapy')",
                        size=None,
                    ),
                ),
                (
                    "context_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Terms describing the context/setting (e.g., 'rural', 'low-income countries')",
                        size=None,
                    ),
                ),
                (
                    "search_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration for domains, file types, and search parameters",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_strategy",
                        to="review_manager.searchsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Strategy",
                "verbose_name_plural": "Search Strategies",
                "db_table": "search_strategies",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_text",
                    models.TextField(help_text="The complete search query string"),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("domain-specific", "Domain Specific"),
                            ("general", "General Search"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain for site-specific searches",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("execution_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("estimated_results", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries_denorm",
                        to="review_manager.searchsession",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="search_strategy.searchstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "db_table": "search_queries",
                "ordering": ["execution_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the template", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when to use this template"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category for organizing templates",
                        max_length=100,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this template is available to all users",
                    ),
                ),
                (
                    "population_template",
                    models.TextField(
                        blank=True,
                        help_text="Population template with placeholders (e.g., '{age_group} with {condition}')",
                    ),
                ),
                (
                    "interest_template",
                    models.TextField(
                        blank=True, help_text="Interest/Intervention template"
                    ),
                ),
                (
                    "context_template",
                    models.TextField(blank=True, help_text="Context template"),
                ),
                (
                    "default_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Default keywords to include",
                    ),
                ),
                (
                    "default_exclusions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Default keywords to exclude",
                    ),
                ),
                (
                    "default_engines",
                    models.JSONField(
                        blank=True, default=list, help_text="Default search engines"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "query_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="searchstrategy",
            index=models.Index(
                fields=["session"], name="search_stra_session_d75ea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchstrategy",
            index=models.Index(fields=["user"], name="search_stra_user_id_5455c9_idx"),
        ),
        migrations.AddIndex(
            model_name="searchstrategy",
            index=models.Index(
                fields=["is_complete"], name="search_stra_is_comp_51831c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["strategy"], name="search_quer_strateg_95b415_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["is_active"], name="search_quer_is_acti_bc2550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytemplate",
            index=models.Index(
                fields=["is_public", "category"], name="query_templ_is_publ_f9d435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytemplate",
            index=models.Index(
                fields=["created_by"], name="query_templ_created_21dcce_idx"
            ),
        ),
    ]
